### DISCUSSION TITLE
Change webpage size (CSS)

### DISCUSSION THREAD

**Discussion by fazoleJH** [sindresorhus/Plash#129] [Q&A] [answered]
Hey. I have set up my second monitor to display a web page. When I hide all windows via F11, the macOS interface makes a kind of semi-transparent border. But it interferes with the web page. I'd like to shrink that web page view by about 10% to make it easier to navigate and read. I tried to do this via CSS code ":root {margin: 10% !important;}", but it doesn't work. Can you please advise me where I am going wrong? I have macOS 12.6.5 (Monterey). Thank you.

**Comment by sindresorhus** [comment, marked as answer]
Try this CSS:

```css
:root {
	width: 90% !important;
	height: 90% !important;
	transform: scale(0.9) !important;
	zoom: 1.1 !important;
	background: transparent !important;
}
```
